services:
  appa:
    build:
      context: ./appa
      dockerfile: Dockerfile
    ports:
      - "8091:8091" # Port exposé pour App A
    restart: always
    networks:
      - power-network

  appb:
    build:
      context: ./appb
      dockerfile: Dockerfile
    ports:
      - "8092:8092" # Port exposé pour App B
    depends_on:
      - appa
    restart: always
    networks:
      - power-network

  appc:
    build:
      context: ./appc
      dockerfile: Dockerfile
    ports:
      - "8093:8093" # Port exposé pour App B 
    restart: always
    networks:
      - power-network
networks:
  power-network:
    driver: bridge
