#Base de donnees en ligne
POSTGRESQL_USERNAME: user_douane
POSTGRESQL_PASSWORD: mot_de_passe_douane
POSTGRESQL_HOST: 192.168.1.209
POSTGRESQL_PORT: 5432
POSTGRESQL_DATABASE: ara_online

#Server
CONTAINER_PORT: 8085
ACTIVE_PROFILE: prod

#Configuration email
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID:
EMAIL_PASSWORD:
VERIFY_EMAIL_HOST: http://localhost:5173,

JWT_EXPIRATION: 432_000_000
JWT_SECRET: ${SECRET}